/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

public class proj2 {
	public static void main(String[] args) {
		int fib=0,
		    tot=1,
		    sum = 0;
		while(tot<4000000){
			if((tot=fib+(fib=tot))%2==0)sum+=tot;
		}
		System.out.println(sum);
	}
}